### ISSUE TITLE
Reopen connection on close

### ISSUE THREAD

**Issue by nkint** [shokai/blendmicro-node#4]
Hi! I'm using the "echo.js" example with a Blend Micro board.

Sometimes it happens to me that the connection close after 20-30 seconds. I have to stop the echo.js (via CTRL+C) and restart it via `$node echo.js` and it start again.

On Arduino side I have this message error:
```
data transmmit success!  Length: 15    Data Credit available: 1
Evt Disconnected/Advertising timed out
Advertising started
```

How to reconnect it automatically?

**Comment by shokai** [comment]
implemented
